import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.platform': 'Platform',
    'nav.agency': 'Agency',
    'nav.services': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.caseStudies': 'Case Studies',
    'nav.getStarted': 'Get Started',
    'nav.getAccess': 'Get Access',
    
    // Footer
    'footer.desc': "Hong Kong's leading PropTech company. AI-powered CRM platform and full-service marketing agency for elite real estate professionals.",
    'footer.explore': 'Explore',
    'footer.connect': 'Connect',
    'footer.rights': 'All rights reserved.',
    
    // Home
    'home.badge': 'CRM Platform + Marketing Agency',
    'home.hero.title': 'One Platform. One Agency.',
    'home.hero.subtitle': 'Everything You Need to Win.',
    'home.hero.desc': 'BasisHK combines a powerful AI-driven CRM platform with a full-service real estate marketing agency — so you can manage listings, capture leads, and dominate your market from a single partner.',
    'home.hero.cta.explore': 'Explore the Platform',
    'home.hero.cta.demo': 'Schedule a Consult',
    'home.float.roi': 'Campaign ROI',
    'home.float.industry': 'vs. industry avg.',
    'home.float.lead': 'New Lead Qualified',
    'home.float.budget': 'Budget',
    'home.pillars.title': 'Two Powerful Offerings',
    'home.pillars.desc': 'Whether you need technology, marketing expertise, or both — BasisHK has you covered.',
    'home.pillars.video.title': 'CRM Platform',
    'home.pillars.video.desc': 'Manage listings, track leads, and automate your workflow with our AI-powered real estate CRM.',
    'home.pillars.video.detail': 'Upload listings, auto-sync across portals, capture and qualify leads 24/7 with AI chatbots, and track everything from a single dashboard. Built specifically for Hong Kong agents.',
    'home.pillars.agents.title': 'Marketing Agency',
    'home.pillars.agents.desc': 'From cinematic AI videos to targeted ad campaigns, our agency handles your entire marketing operation.',
    'home.pillars.agents.detail': 'Professional video production, social media content, drone editing, virtual staging, predictive ad targeting, and a dedicated account manager — all done for you.',
    'home.pillars.predictive.title': 'Better Together',
    'home.pillars.predictive.desc': 'Combine the platform and agency for a fully integrated, end-to-end growth engine.',
    'home.pillars.predictive.detail': 'When your CRM captures a lead, our agency nurtures it. When our agency generates content, your platform distributes it. The result: a seamless pipeline from first impression to closed deal.',

    'home.how.title': 'How It Works',
    'home.how.desc': 'A streamlined three-step process to transform your lead generation.',
    'home.how.1.title': 'Connect',
    'home.how.1.desc': 'Integrate your listings and social profiles with our secure platform.',
    'home.how.1.detail': 'We integrate directly with your Facebook and Instagram accounts. Simply upload your property photos and key selling points to our secure dashboard.',
    'home.how.2.title': 'Automate',
    'home.how.2.desc': 'Our AI generates content and launches targeted campaigns instantly.',
    'home.how.2.detail': 'Our system automatically generates professional video ads, writes compelling copy, and sets up targeted ad campaigns optimized for your specific audience.',
    'home.how.3.title': 'Convert',
    'home.how.3.desc': 'Receive pre-qualified leads directly to your phone, ready to view.',
    'home.how.3.detail': 'Sit back as high-quality leads start flowing in. You get instant notifications for booked viewings and hot leads ready to buy.',
    'home.pain.title': 'Stop Relying on',
    'home.pain.subtitle': 'Outdated Methods',
    'home.pain.1': 'Portal saturation means your listings get buried.',
    'home.pain.2': 'Manual follow-ups are too slow for modern buyers.',
    'home.pain.3': 'Generic ads waste budget on unqualified clicks.',
    'home.solution.title': 'The BasisHK Solution',
    'home.solution.1.title': 'Dominance',
    'home.solution.1.desc': 'Own the feed with high-frequency video content.',
    'home.solution.2.title': 'Speed',
    'home.solution.2.desc': 'Respond in seconds, not hours, with automation.',
    'home.solution.3.title': 'Precision',
    'home.solution.3.desc': 'Target only the top 1% of qualified buyers.',
    'home.video.title': 'The Future Of',
    'home.video.subtitle': 'Real Estate Marketing',
    'home.video.desc': 'Experience the next generation of property marketing. AI-powered videos, intelligent targeting, and automated lead generation - all working together to transform your business.',
    'home.video.cta': 'Get Started Today',
    'home.cta.title': 'Ready to',
    'home.cta.subtitle': 'Modernize?',
    'home.cta.desc': 'Join the top 1% of agents using our CRM platform and marketing agency to dominate the market.',
    'home.cta.button': 'Start Now',
    'home.trusted.title': 'Trusted by Agents from Top Developers',
    'home.gallery.title': 'Cinematic Excellence',
    'home.gallery.subtitle': 'See what our AI can create for your listings.',
    'home.gallery.tag.luxury': 'Luxury',
    'home.gallery.tag.tour': 'Virtual Tour',
    'home.gallery.tag.promo': 'Social Promo',
    'home.gallery.tag.drone': 'Drone View',

    // Case Studies
    'home.cases.title': 'Proven Results',
    'home.cases.subtitle': 'Real success stories from Hong Kong agents.',
    'home.cases.midlevels.title': 'Mid-Levels Luxury',
    'home.cases.midlevels.desc': 'Cinematic video property content generated 15k+ organic views.',
    'home.cases.midlevels.stat1': '15k+',
    'home.cases.midlevels.label1': 'Video Views',
    'home.cases.midlevels.stat2': '14 Days',
    'home.cases.midlevels.label2': 'Time to Sell',
    'home.cases.kaitak.title': 'Kai Tak Investment',
    'home.cases.kaitak.desc': 'Vertical video ads drove 45 leads in 48 hours.',
    'home.cases.kaitak.stat1': '45 Leads',
    'home.cases.kaitak.label1': 'Volume',
    'home.cases.kaitak.stat2': '$12',
    'home.cases.kaitak.label2': 'Cost Per Lead',
    'home.cases.saikung.title': 'Sai Kung Villa',
    'home.cases.saikung.desc': 'Drone showcase captured 12 high-net-worth buyers.',
    'home.cases.saikung.stat1': '12 Buyers',
    'home.cases.saikung.label1': 'Qualified Leads',
    'home.cases.saikung.stat2': '14.2%',
    'home.cases.saikung.label2': 'Engagement Rate',

    // Services
    'services.title': 'Intelligent Infrastructure',
    'services.subtitle': 'Choose the growth engine that fits your scale.',
    'services.monthly': 'Monthly',
    'services.quarterly': 'Quarterly',
    'services.save': 'Save 5%',
    'services.plan.starter': 'Starter',
    'services.plan.growth': 'Growth',
    'services.plan.agency': 'Agency',
    'services.plan.starter.desc': 'Essential automation for individual agents.',
    'services.plan.growth.desc': 'Advanced tools for high-volume producers.',
    'services.plan.agency.desc': 'Full-scale infrastructure for teams.',
    'services.feature.video': 'AI Property Videos',
    'services.feature.bot': 'Lead Capture Bot',
    'services.feature.content': 'Social Media Content',
    'services.feature.consultancy': 'Property Ad Consultancy',
    'services.feature.report': 'Performance Report',
    'services.feature.support': 'Email Support',
    'services.feature.manager': 'Dedicated Account Manager',
    'services.feature.basic': 'Basic',
    'services.feature.advanced': 'Advanced',
    'services.feature.posts': 'Posts',
    'services.feature.monthly': 'Monthly',
    'services.feature.revisions': 'Unlimited Revisions',
    'services.feature.weekly': 'Weekly',
    'services.feature.aiOptimizer': 'AI Property Listing Optimizer',
    'services.feature.basicPortal': 'Custom Branded Property Portal',
    'services.feature.limitedListings': 'Limited Listings + Auto Sync',
    'services.feature.unlimitedListings': 'Unlimited Listings + Auto Sync',
    'services.feature.adsBoosting2k': 'Ads Boosting Service (Worth $2,000)',
    'services.feature.adsBoosting4k': 'Ads Boosting Service (Worth $4,000)',
    'services.feature.videos': 'Videos',
    'services.plan.videoOnly': 'Custom AI Property Videos',
    'services.plan.videoOnly.desc': 'Need videos only? Get high-quality AI-generated property videos without a subscription.',
    'services.videoSlider.label': 'Select number of videos',
    'services.videoSlider.perVideo': 'per video',
    'services.videoOnly.feature1': '4K Cinematic Quality',
    'services.videoOnly.feature2': 'Professional Voiceover',
    'services.videoOnly.feature3': '48-Hour Delivery',
    'services.videoOnly.feature4': 'Unlimited Revisions',
    'services.videoOnly.cta': 'Order Videos Now',
    'services.select': 'Select Plan',
    'services.popular': 'Most Popular',
    'services.faq.title': 'Frequently Asked Questions',
    'services.faq.subtitle': 'Everything you need to know about our services and billing.',
    'services.faq.q1': 'What does "Unlimited Revisions" mean?',
    'services.faq.a1': 'We want you to be 100% satisfied with your content. You can request as many changes as needed to the video edits, captions, or ad copy until it perfectly matches your vision.',
    'services.faq.q2': 'Is there a minimum contract period?',
    'services.faq.a2': 'No, all our plans are month-to-month. You can cancel or upgrade at any time. However, choosing quarterly billing saves you 5%.',
    'services.faq.q3': 'How quickly can I get my first video?',
    'services.faq.a3': 'Once you upload your property photos, our AI generates the initial draft within minutes. After your review, the final polished version is typically ready within 48 hours ready for revisions by our creative team.',
    'services.faq.q4': 'Do you handle the ad spend budget?',
    'services.faq.a4': 'The ad spend is paid directly to the platforms (Facebook/Instagram) by you. Our fee covers the management, optimization, and creative production.',
    'services.faq.q5': 'What is the Advanced Lead Capture Bot?',
    'services.faq.a5': 'Our Advanced Lead Capture Bot is an AI-powered assistant that engages visitors 24/7. It qualifies leads by asking key questions about their budget, preferences, and timeline, ensuring you only spend time on high-intent prospects.',
    'services.faq.q6': 'How does Predictive Targeting work?',
    'services.faq.a6': 'Predictive Targeting uses machine learning to analyze market trends and user behavior. It identifies potential buyers who are most likely to convert, allowing us to serve your ads to the most relevant audience before your competitors do.',
    'services.faq.q7': 'What does a Dedicated Account Manager do?',
    'services.faq.a7': 'Your Dedicated Account Manager is your strategic partner. They oversee your campaigns, provide monthly performance reports, and offer personalized advice to optimize your marketing strategy, ensuring your goals are met.',

    // About
    'about.title': 'Built by Agents, For Agents',
    'about.desc': 'We are not just tech developers. We are real estate veterans who understand the hustle.',
    'about.mission.1': 'BasisHK was born from frustration. As former agents in Hong Kong\'s cutthroat market, we saw how traditional marketing failed to keep up with the digital age. We needed two things: a smarter CRM and a better marketing partner.',
    'about.mission.2': 'So we built both. Our AI-powered CRM platform handles listing management, lead tracking, and automated follow-ups. Our marketing agency produces cinematic videos, runs targeted ad campaigns, and creates content that converts.',
    'about.mission.3': 'Today, BasisHK is the only company in Hong Kong that offers both a real estate CRM platform and a full-service marketing agency under one roof — giving agents an unfair advantage.',
    'about.stat.focus': 'Real Estate Focus',
    'about.stat.uptime': 'System Uptime',
    'about.stat.growth': 'Dedicated to Your Growth',
    'about.values.title': 'Our Core Values',
    'about.values.integrity': 'Agent-First',
    'about.values.integrity.desc': 'We build features that solve real problems, not just shiny toys.',
    'about.values.innovation': 'Transparency',
    'about.values.innovation.desc': 'No hidden fees or vanity metrics. We track what makes you money.',
    'about.values.results': 'Excellence',
    'about.values.results.desc': 'We believe every agent deserves world-class infrastructure.',
    'about.slogan.title': 'In Content We Trust',
    'about.slogan.desc': 'In the age of algorithms and automation, authentic content remains the cornerstone of meaningful connections. We believe that compelling stories, stunning visuals, and genuine value creation are what truly move buyers to action. Technology amplifies our reach, but it is the quality of our content that builds trust, establishes authority, and ultimately closes deals.',
    'about.cta.title': 'Join the Revolution',
    'about.cta.button': 'Get in Touch',

    // Contact
    'contact.title': 'Contact Us',
    'contact.desc': 'Interested in our services? Please fill out the form to schedule a consultation with our marketing team. We look forward to discussing how we can assist in growing your real estate business.',
    'contact.hours.title': 'Office Hours',
    'contact.hours.desc': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.email.title': 'Email',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.agency': 'Real Estate Agency',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.budget': 'Marketing Budget (Monthly)',
    'contact.form.budget.placeholder': 'Select range',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Please describe your current marketing challenges...',
    'contact.form.submit': 'Submit Inquiry',
    'contact.form.submitting': 'Submitting...',
    'contact.toast.title': 'Inquiry Received',
    'contact.toast.desc': 'Thank you for contacting BasisHK. A representative will respond to your inquiry within 24 hours.',
    
    // Contact Form - New Keys
    'contact.step1.title': 'Tell us about yourself',
    'contact.step1.desc': 'Let us know who you are so we can personalize your experience.',
    'contact.step2.title': 'Contact Details',
    'contact.step2.desc': 'How can we reach you to discuss your needs?',
    'contact.step3.title': 'What interests you?',
    'contact.step3.desc': 'Select the services you\'re interested in and tell us more.',
    'contact.info.title': 'Get in Touch',
    'contact.phone.title': 'Phone',
    'contact.response.time': 'We typically respond within 24 hours during business days.',
    'contact.trust.title': 'Why Choose Us',
    'contact.trust.1': 'Trusted by 100+ Hong Kong agents',
    'contact.trust.2': 'No hidden fees or long-term contracts',
    'contact.trust.3': '24/7 dedicated support team',
    'contact.service.video': 'AI Video Property Content',
    'contact.service.video.desc': 'Transform property photos into cinematic videos',
    'contact.service.bot': 'Lead Capture Bot',
    'contact.service.bot.desc': '24/7 automated lead qualification',
    'contact.service.targeting': 'Predictive Targeting',
    'contact.service.targeting.desc': 'Find high-intent buyers automatically',
    'contact.service.consultation': 'Strategy Consultation',
    'contact.service.consultation.desc': 'Personalized marketing advice',
    'contact.form.back': 'Back',
    'contact.form.next': 'Continue',
    'contact.form.success': 'Sent Successfully',
    'contact.error.required': 'This field is required',
    'contact.error.email': 'Please enter a valid email address',
    
    // Platform Page
    'platform.badge': 'CRM Platform',
    'platform.hero.title': 'Your Real Estate',
    'platform.hero.subtitle': 'Command Centre',
    'platform.hero.desc': 'Manage every listing, lead, and conversation from one intelligent dashboard. Our AI-powered CRM is built from the ground up for Hong Kong real estate agents.',
    'platform.hero.cta.pricing': 'View Pricing',
    'platform.hero.cta.demo': 'Book a Demo',
    'platform.features.title': 'Everything You Need to Manage Your Business',
    'platform.features.desc': 'A complete CRM built specifically for real estate — not a generic tool with bolt-on features.',
    'platform.feat.listings.title': 'Listing Management',
    'platform.feat.listings.desc': 'Upload, organize, and manage all your property listings in one place. Add photos, floor plans, pricing, and key details. Keep everything up to date with a single source of truth.',
    'platform.feat.leads.title': 'Lead Tracking & CRM',
    'platform.feat.leads.desc': 'Track every lead from first contact to closed deal. See their browsing history, preferences, budget, and engagement timeline. Never lose a prospect again.',
    'platform.feat.chatbot.title': 'AI Lead Capture Bot',
    'platform.feat.chatbot.desc': 'Our AI chatbot engages visitors on WhatsApp and Messenger 24/7. It qualifies leads by asking about budget, preferences, and timeline — then books viewings directly into your calendar.',
    'platform.feat.sync.title': 'Auto-Sync Across Portals',
    'platform.feat.sync.desc': 'Publish your listings once and auto-sync them across major property portals and your social media channels. Update once, update everywhere.',
    'platform.feat.dashboard.title': 'Performance Dashboard',
    'platform.feat.dashboard.desc': 'Real-time analytics on your listings, leads, and campaigns. See which properties are getting the most attention and where your leads are coming from.',
    'platform.feat.mobile.title': 'Mobile-First Design',
    'platform.feat.mobile.desc': 'Access your CRM on the go. Respond to leads, update listings, and check performance from your phone — because deals don\'t wait for you to get back to the office.',
    'platform.how.title': 'Get Started in 4 Steps',
    'platform.how.desc': 'From sign-up to your first qualified lead in under 48 hours.',
    'platform.how.1.title': 'Sign Up',
    'platform.how.1.desc': 'Choose your plan and create your account. No long-term contracts.',
    'platform.how.2.title': 'Upload Listings',
    'platform.how.2.desc': 'Add your property listings with photos, details, and pricing.',
    'platform.how.3.title': 'Connect Channels',
    'platform.how.3.desc': 'Link your WhatsApp, social media, and property portal accounts.',
    'platform.how.4.title': 'Start Receiving Leads',
    'platform.how.4.desc': 'Our AI chatbot begins capturing and qualifying leads immediately.',
    'platform.why.title': 'Why Our CRM?',
    'platform.why.desc': 'Generic CRMs weren\'t built for real estate. Ours was.',
    'platform.why.1.title': 'Hong Kong Native',
    'platform.why.1.desc': 'Built for the local market with bilingual support, local portal integrations, and HKD pricing.',
    'platform.why.2.title': 'AI-First',
    'platform.why.2.desc': 'Not just a database — our AI actively qualifies leads, suggests follow-ups, and optimizes your workflow.',
    'platform.why.3.title': 'Agency Integration',
    'platform.why.3.desc': 'Seamlessly connects with our marketing agency services for a fully integrated growth engine.',
    'platform.cta.title': 'Ready to Take Control?',
    'platform.cta.desc': 'Start managing your listings and leads with the smartest CRM in Hong Kong real estate.',
    'platform.cta.button': 'View Plans',
    'platform.cta.agency': 'Explore Our Agency',

    // Agency Page
    'agency.badge': 'Marketing Agency',
    'agency.hero.title': 'We Handle Your',
    'agency.hero.subtitle': 'Entire Marketing Operation',
    'agency.hero.desc': 'From AI-powered video production to precision ad targeting, our full-service marketing agency does the heavy lifting so you can focus on closing deals.',
    'agency.hero.cta.services': 'View Services & Pricing',
    'agency.hero.cta.consult': 'Book a Consultation',
    'agency.services.title': 'Full-Service Marketing',
    'agency.services.desc': 'Everything a modern real estate agent needs to dominate their market — done for you.',
    'agency.svc.video.title': 'AI Video Production',
    'agency.svc.video.desc': 'We transform your property photos into cinematic video tours with professional voiceovers, music, and dynamic transitions. Delivered in 48 hours, no film crew needed.',
    'agency.svc.ads.title': 'Predictive Ad Targeting',
    'agency.svc.ads.desc': 'Our algorithms analyze thousands of data points to find high-intent buyers. We run and optimize your Facebook and Instagram campaigns for maximum ROI.',
    'agency.svc.content.title': 'Social Media Content',
    'agency.svc.content.desc': 'We create and manage your social media presence with professional posts, stories, and reels tailored to your brand and market.',
    'agency.svc.drone.title': 'Drone Video Editing',
    'agency.svc.drone.desc': 'Send us your raw drone footage and we\'ll transform it into a cinematic aerial showcase with color grading, music, and professional graphics.',
    'agency.svc.staging.title': 'Virtual Staging',
    'agency.svc.staging.desc': 'Digitally furnish empty rooms to help buyers visualize the potential. The most cost-effective way to make properties feel like home.',
    'agency.svc.social.title': 'Social Media Management',
    'agency.svc.social.desc': 'We handle your entire social media strategy — content calendar, posting schedule, community engagement, and performance reporting.',
    'agency.addons.title': 'Add-On Services',
    'agency.addons.desc': 'One-off services you can purchase anytime to boost specific listings or campaigns.',
    'agency.addon.videopack.title': 'Extra Video Pack',
    'agency.addon.videopack.desc': '10 additional AI-generated property videos.',
    'agency.addon.imagepack.title': 'Extra Image Pack',
    'agency.addon.imagepack.desc': '50 professionally enhanced property images.',
    'agency.addon.voiceover.title': 'Premium Voiceover',
    'agency.addon.voiceover.desc': 'Professional Cantonese AI voiceover for your videos.',
    'agency.addon.staging.title': 'Virtual Staging',
    'agency.addon.staging.desc': 'Digital furnishing per room for empty properties.',
    'agency.addon.drone.title': 'Drone Video Editing',
    'agency.addon.drone.desc': 'Professional editing of your raw drone footage.',
    'agency.addon.social.title': 'Social Media Pack',
    'agency.addon.social.desc': 'Monthly social media content package.',
    'agency.addon.portal.title': 'Branded Portal',
    'agency.addon.portal.desc': 'Custom-branded property portal setup.',
    'agency.addon.rush.title': 'Priority Rendering',
    'agency.addon.rush.desc': 'Rush delivery for urgent video projects.',
    'agency.results.title': 'Real Results',
    'agency.results.desc': 'Our clients see measurable, verifiable results from day one.',
    'agency.results.roi': 'Average Campaign ROI',
    'agency.results.delivery': 'Video Delivery Time',
    'agency.results.cpl': 'Average Cost Per Lead',
    'agency.cta.title': 'Let Us Handle Your Marketing',
    'agency.cta.desc': 'Book a free consultation and see how our agency can transform your business.',
    'agency.cta.button': 'Book Consultation',
    'agency.cta.platform': 'Explore Our CRM Platform',

    // Thank You
    'thankyou.title': 'Thank You!',
    'thankyou.subtitle': 'Your message has been received.',
    'thankyou.desc': 'We have sent a confirmation email to your inbox. While you wait, why not schedule a free 15-minute strategy call with our team?',
    'thankyou.button': 'Book Consultation',
    'thankyou.back': 'Back to Home',
  },
  zh: {
    // Navigation
    'nav.home': '首頁',
    'nav.platform': '平台',
    'nav.agency': '營銷代理',
    'nav.services': '收費方案',
    'nav.about': '關於我們',
    'nav.contact': '聯絡我們',
    'nav.blog': '博客',
    'nav.caseStudies': '成功案例',
    'nav.getStarted': '免費諮詢',
    'nav.getAccess': '立即體驗',
    
    // Footer
    'footer.desc': "香港領先的地產科技公司。AI 驅動 CRM 平台及全方位營銷代理，專為精英地產代理而設。",
    'footer.explore': '快速連結',
    'footer.connect': '聯絡我們',
    'footer.rights': '版權所有',
    
    // Home
    'home.badge': 'CRM 平台 + 營銷代理',
    'home.hero.title': '一個平台。一個代理。',
    'home.hero.subtitle': '助您贏盡市場。',
    'home.hero.desc': 'BasisHK 結合強大的 AI 驅動 CRM 平台與全方位地產營銷代理 — 讓您從一個合作夥伴管理樓盤、捕獲客源、稱霸市場。',
    'home.hero.cta.explore': '探索平台',
    'home.hero.cta.demo': '預約免費諮詢',
    'home.float.roi': '廣告回報率',
    'home.float.industry': '高於行業平均',
    'home.float.lead': '新增有效客源',
    'home.float.budget': '廣告預算',
    'home.pillars.title': '兩大核心服務',
    'home.pillars.desc': '無論您需要科技工具、營銷專業，還是兩者兼備 — BasisHK 都能滿足。',
    'home.pillars.video.title': 'CRM 平台',
    'home.pillars.video.desc': '透過 AI 驅動的地產 CRM 管理樓盤、追蹤客源、自動化工作流程。',
    'home.pillars.video.detail': '上傳樓盤、跨平台自動同步、透過 AI 聊天機械人全天候捕獲及篩選客源，並從單一儀表板追蹤一切。專為香港代理而設。',
    'home.pillars.agents.title': '營銷代理',
    'home.pillars.agents.desc': '從電影級 AI 影片到精準廣告投放，我們的代理團隊為您處理整個營銷運作。',
    'home.pillars.agents.detail': '專業影片製作、社交媒體內容、航拍剪輯、虛擬佈置、精準廣告投放及專屬客戶經理 — 全部為您代勞。',
    'home.pillars.predictive.title': '強強聯手',
    'home.pillars.predictive.desc': '結合平台與代理，打造全方位一站式增長引擎。',
    'home.pillars.predictive.detail': '當 CRM 捕獲客源時，我們的代理團隊負責跟進培育。當代理團隊製作內容時，您的平台負責分發。結果：從第一印象到成交的無縫銷售管道。',

    'home.how.title': '如何運作',
    'home.how.desc': '簡單三步，全面提升您的接単效率。',
    'home.how.1.title': '連接帳戶',
    'home.how.1.desc': '將您的樓盤資料及社交媒體帳戶與我們的平台整合。',
    'home.how.1.detail': '直接連接您的 Facebook 及 Instagram 帳戶，上傳樓盤照片及賣點資料到我們的安全平台即可。',
    'home.how.2.title': '自動推廣',
    'home.how.2.desc': 'AI 系統即時生成內容並啟動精準廣告投放。',
    'home.how.2.detail': '系統自動製作專業影片廣告、撰寫吸睛文案，並針對您的目標客群進行精準投放。',
    'home.how.3.title': '接收客源',
    'home.how.3.desc': '經篩選的優質客源直接傳送到您的手機，隨時安排睅樓。',
    'home.how.3.detail': '坐等優質客源上門。您會即時收到已預約睅樓及有意向買家的通知。',
    'home.pain.title': '告別',
    'home.pain.subtitle': '傳統營銷的困境',
    'home.pain.1': '地產平台競爭激烈，您的樓盤很容易被淹沒。',
    'home.pain.2': '人手跟進速度太慢，跟不上現代買家的節奏。',
    'home.pain.3': '廣泛投放廣告浪費預算，難以觸及真正有意向的買家。',
    'home.solution.title': 'BasisHK 為您解決',
    'home.solution.1.title': '曝光率',
    'home.solution.1.desc': '以高頻率影片內容搶佔社交媒體版面。',
    'home.solution.2.title': '回應速度',
    'home.solution.2.desc': '自動化系統即時回應，不再讓客戶等待。',
    'home.solution.3.title': '精準投放',
    'home.solution.3.desc': '只將廣告投放給最有可能成交的買家。',
    'home.video.title': '地產營銷的',
    'home.video.subtitle': '未來已來',
    'home.video.desc': '體驗新一代物業營銷。AI影片製作、智能客源定位、自動化客戶開發 - 全方位提升您的業務。',
    'home.video.cta': '立即開始',
    'home.cta.title': '準備好',
    'home.cta.subtitle': '升級您的營銷策略？',
    'home.cta.desc': '加入頂尖代理行列，透過我們的 CRM 平台及營銷代理稱霸市場。',
    'home.cta.button': '立即開始',
    'home.trusted.title': '深受頂尖發展商代理信賴',
    'home.gallery.title': '電影級影片製作',
    'home.gallery.subtitle': '看看我們的 AI 能為您的樓盤帶來什麼效果。',
    'home.gallery.tag.luxury': '豪宅',
    'home.gallery.tag.tour': '虛擬導覽',
    'home.gallery.tag.promo': '社交推廣',
    'home.gallery.tag.drone': '航拍景觀',

    // Case Studies
    'home.cases.title': '實戰案例',
    'home.cases.subtitle': '香港代理的真實成功經驗。',
    'home.cases.midlevels.title': '半山豪宅',
    'home.cases.midlevels.desc': '電影級影片導覽獲得超過 1.5 萬次自然觀看。',
    'home.cases.midlevels.stat1': '1.5 萬+',
    'home.cases.midlevels.label1': '影片觀看次數',
    'home.cases.midlevels.stat2': '14 天',
    'home.cases.midlevels.label2': '成功售出',
    'home.cases.kaitak.title': '啟德新盤',
    'home.cases.kaitak.desc': '直式影片廣告 48 小時內帶來 45 個有效客源。',
    'home.cases.kaitak.stat1': '45 個',
    'home.cases.kaitak.label1': '有效客源',
    'home.cases.kaitak.stat2': '$12',
    'home.cases.kaitak.label2': '每個客源成本',
    'home.cases.saikung.title': '西貢別墅',
    'home.cases.saikung.desc': '航拍展示成功吸引 12 位高資產買家。',
    'home.cases.saikung.stat1': '12 位',
    'home.cases.saikung.label1': '優質買家',
    'home.cases.saikung.stat2': '14.2%',
    'home.cases.saikung.label2': '互動率',

    // Services
    'services.title': '服務方案',
    'services.subtitle': '選擇最適合您的營銷方案。',
    'services.monthly': '月費',
    'services.quarterly': '季費',
    'services.save': '節省 5%',
    'services.plan.starter': '入門方案',
    'services.plan.growth': '進階方案',
    'services.plan.agency': '團隊方案',
    'services.plan.starter.desc': '適合個人代理的基本配套。',
    'services.plan.growth.desc': '適合高效率代理的全面配套。',
    'services.plan.agency.desc': '適合團隊的企業級方案。',
    'services.feature.video': 'AI 樓盤影片',
    'services.feature.bot': '智能客源跟進',
    'services.feature.content': '社交媒體內容',
    'services.feature.consultancy': '廣告策略諮詢',
    'services.feature.report': '效果報告',
    'services.feature.support': '電郵支援',
    'services.feature.manager': '專屬客戶經理',
    'services.feature.basic': '基本版',
    'services.feature.advanced': '進階版',
    'services.feature.posts': '篇貼文',
    'services.feature.monthly': '每月',
    'services.feature.revisions': '無限次修改',
    'services.feature.weekly': '每週',
    'services.feature.aiOptimizer': 'AI 樓盤列表優化',
    'services.feature.basicPortal': '專屬品牌樓盤網頁',
    'services.feature.limitedListings': '樓盤數量有限 + 自動同步',
    'services.feature.unlimitedListings': '無限樓盤數量 + 自動同步',
    'services.feature.adsBoosting2k': '廣告推廣服務（價值 $2,000）',
    'services.feature.adsBoosting4k': '廣告推廣服務（價值 $4,000）',
    'services.feature.videos': '條影片',
    'services.plan.videoOnly': '單點 AI 樓盤影片',
    'services.plan.videoOnly.desc': '只需要影片？無需訂閱，即可獲得高質素 AI 樓盤影片。',
    'services.videoSlider.label': '選擇影片數量',
    'services.videoSlider.perVideo': '每條影片',
    'services.videoOnly.feature1': '4K 電影級畫質',
    'services.videoOnly.feature2': '專業旁白配音',
    'services.videoOnly.feature3': '48 小時內交付',
    'services.videoOnly.feature4': '無限次修改',
    'services.videoOnly.cta': '立即訂購',
    'services.select': '選擇此方案',
    'services.popular': '最多人選擇',
    'services.faq.title': '常見問題',
    'services.faq.subtitle': '關於我們服務的常見疑問。',
    'services.faq.q1': '「無限次修改」具體是什麼？',
    'services.faq.a1': '我們希望您對成品完全滿意。您可以無限次要求修改影片剪輯、字幕或廣告文案，直到完全符合您的要求。',
    'services.faq.q2': '有最短合約期限嗎？',
    'services.faq.a2': '沒有。所有方案均按月收費，可隨時取消或升級。選擇季費可節省 5%。',
    'services.faq.q3': '多快可以收到第一條影片？',
    'services.faq.a3': '上傳樓盤照片後，AI 系統數分鐘內即可生成初稿。經您確認後，創意團隊通常在 48 小時內完成最終版本。',
    'services.faq.q4': '廣告預算如何處理？',
    'services.faq.a4': '廣告費用由您直接支付給 Facebook/Instagram 平台。我們的服務費包含廣告管理、優化及創意製作。',
    'services.faq.q5': '什麼是進階版智能客源跟進？',
    'services.faq.a5': '這是一個 24 小時運作的 AI 助理，會自動詢問潛在客戶的預算、偏好及時間表，確保您只需處理真正有意向的買家。',
    'services.faq.q6': '精準廣告投放是如何運作的？',
    'services.faq.a6': '我們透過機器學習分析市場趨勢及用戶行為，找出最有可能成交的潛在買家，讓您的廣告投放更精準有效。',
    'services.faq.q7': '專屬客戶經理提供什麼服務？',
    'services.faq.a7': '您的專屬客戶經理是您的營銷夥伴，負責監督廣告投放、提供每月效果報告，並給予個人化的營銷建議，協助您達成業績目標。',

    // About
    'about.title': '由代理創立，為代理服務',
    'about.desc': '我們不僅是技術團隊，更是深諳地產行業的實戰者。',
    'about.mission.1': 'BasisHK 誕生於實戰經驗。作為曾在香港競爭激烈的地產市場打拼的前線代理，我們深知傳統營銷方式已無法滿足數碼時代的需求。我們需要兩樣東西：更聰明的 CRM 和更好的營銷夥伴。',
    'about.mission.2': '所以我們兩者都建立了。我們的 AI 驅動 CRM 平台處理樓盤管理、客源追蹤和自動跟進。我們的營銷代理製作電影級影片、投放精準廣告、創作能促成交易的內容。',
    'about.mission.3': '如今，BasisHK 是香港唯一一家同時提供地產 CRM 平台和全方位營銷代理的公司 — 讓代理擁有不公平的競爭優勢。',
    'about.stat.focus': '專注地產行業',
    'about.stat.uptime': '系統穩定運作',
    'about.stat.growth': '助您業績增長',
    'about.values.title': '核心理念',
    'about.values.integrity': '代理優先',
    'about.values.integrity.desc': '我們開發的每個功能都是為了解決代理的實際問題，而非華而不實的噒頭。',
    'about.values.innovation': '費用透明',
    'about.values.innovation.desc': '絕無隱藏收費或虛假數據。我們只追蹤能為您帶來實際收益的指標。',
    'about.values.results': '追求卓越',
    'about.values.results.desc': '我們相信每位代理都應該擁有世界級的營銷工具。',
    'about.slogan.title': '內容為本',
    'about.slogan.desc': '在演算法與自動化的時代，優質內容仍然是建立客戶信任的基石。我們深信，引人入勝的故事、令人驚豔的視覺效果、以及真正的價值創造，才是推動買家行動的關鍵。科技擴大了我們的觸及範圍，但內容的質素才是建立信任、樹立專業形象、最終促成交易的決定性因素。',
    'about.cta.title': '加入我們',
    'about.cta.button': '立即聯絡',

    // Contact
    'contact.title': '聯絡我們',
    'contact.desc': '對我們的服務有興趣？請填寫以下表格，我們的團隊會儘快與您聯絡，討論如何協助您提升業績。',
    'contact.hours.title': '辦公時間',
    'contact.hours.desc': '星期一至五：上午 9:00 - 下午 6:00',
    'contact.email.title': '電郵',
    'contact.form.firstName': '名字',
    'contact.form.lastName': '姓氏',
    'contact.form.agency': '所屬公司',
    'contact.form.email': '電郵地址',
    'contact.form.phone': '聯絡電話',
    'contact.form.budget': '每月營銷預算',
    'contact.form.budget.placeholder': '請選擇',
    'contact.form.message': '訊息內容',
    'contact.form.message.placeholder': '請簡述您目前面對的營銷挑戰...',
    'contact.form.submit': '提交查詢',
    'contact.form.submitting': '提交中...',
    'contact.toast.title': '已收到您的查詢',
    'contact.toast.desc': '感謝您的聯絡！我們的團隊會在 24 小時內回覆您。',
    
    // Contact Form - New Keys
    'contact.step1.title': '請告訴我們您的資料',
    'contact.step1.desc': '讓我們更了解您，提供更貼心的服務。',
    'contact.step2.title': '聯絡方式',
    'contact.step2.desc': '您希望我們如何與您聯絡？',
    'contact.step3.title': '您對哪些服務有興趣？',
    'contact.step3.desc': '選擇您感興趣的服務，並告訴我們更多您的需求。',
    'contact.info.title': '聯絡資訊',
    'contact.phone.title': '電話',
    'contact.response.time': '我們通常會在工作日 24 小時內回覆。',
    'contact.trust.title': '為何選擇我們',
    'contact.trust.1': '超過 100 位香港代理信賴',
    'contact.trust.2': '無隱藏費用，無長期合約',
    'contact.trust.3': '全天候專屬支援團隊',
    'contact.service.video': 'AI 影片製作',
    'contact.service.video.desc': '將樓盤照片轉化為電影級宣傳影片',
    'contact.service.bot': '智能客源跟進',
    'contact.service.bot.desc': '24 小時自動篩選及跟進客源',
    'contact.service.targeting': '精準廣告投放',
    'contact.service.targeting.desc': '自動找出有意向的目標買家',
    'contact.service.consultation': '營銷策略諮詢',
    'contact.service.consultation.desc': '量身訂造的營銷建議',
    'contact.form.back': '上一步',
    'contact.form.next': '下一步',
    'contact.form.success': '提交成功',
    'contact.error.required': '此欄位為必填',
    'contact.error.email': '請輸入有效的電郵地址',

    // Platform Page
    'platform.badge': 'CRM 平台',
    'platform.hero.title': '您的地產',
    'platform.hero.subtitle': '指揮中心',
    'platform.hero.desc': '從一個智能儀表板管理每個樓盤、客源和對話。我們的 AI 驅動 CRM 從零開始為香港地產代理打造。',
    'platform.hero.cta.pricing': '查看收費',
    'platform.hero.cta.demo': '預約示範',
    'platform.features.title': '管理業務所需的一切',
    'platform.features.desc': '專為地產而建的完整 CRM — 而非附加功能的通用工具。',
    'platform.feat.listings.title': '樓盤管理',
    'platform.feat.listings.desc': '在一個地方上傳、整理和管理所有樓盤。添加照片、平面圖、定價和關鍵資料。以單一真實來源保持一切最新。',
    'platform.feat.leads.title': '客源追蹤 & CRM',
    'platform.feat.leads.desc': '追蹤每個客源從首次接觸到成交。查看他們的瀏覽記錄、偏好、預算和互動時間線。再也不會失去潛在客戶。',
    'platform.feat.chatbot.title': 'AI 智能客源機械人',
    'platform.feat.chatbot.desc': '我們的 AI 聊天機械人全天候在 WhatsApp 和 Messenger 上與訪客互動。它會詢問預算、偏好和時間表來篩選客源 — 然後直接在您的日曆中預約睇樓。',
    'platform.feat.sync.title': '跨平台自動同步',
    'platform.feat.sync.desc': '發佈一次樓盤，自動同步到各大地產平台和您的社交媒體頻道。更新一次，全部更新。',
    'platform.feat.dashboard.title': '效能儀表板',
    'platform.feat.dashboard.desc': '即時分析您的樓盤、客源和廣告活動數據。查看哪些物業最受關注，以及客源來自哪裡。',
    'platform.feat.mobile.title': '流動優先設計',
    'platform.feat.mobile.desc': '隨時隨地使用 CRM。從手機回覆客源、更新樓盤、查看效能 — 因為交易不會等您回到辦公室。',
    'platform.how.title': '4 步輕鬆開始',
    'platform.how.desc': '從註冊到收到第一個合格客源，不到 48 小時。',
    'platform.how.1.title': '註冊帳戶',
    'platform.how.1.desc': '選擇方案並創建帳戶。無需長期合約。',
    'platform.how.2.title': '上傳樓盤',
    'platform.how.2.desc': '添加您的樓盤資料，包括照片、詳情和定價。',
    'platform.how.3.title': '連接渠道',
    'platform.how.3.desc': '連結您的 WhatsApp、社交媒體和地產平台帳戶。',
    'platform.how.4.title': '開始接收客源',
    'platform.how.4.desc': '我們的 AI 機械人立即開始捕獲和篩選客源。',
    'platform.why.title': '為何選擇我們的 CRM？',
    'platform.why.desc': '通用 CRM 不是為地產而建的。我們的是。',
    'platform.why.1.title': '香港本地化',
    'platform.why.1.desc': '為本地市場而建，提供雙語支援、本地平台整合及港幣定價。',
    'platform.why.2.title': 'AI 優先',
    'platform.why.2.desc': '不僅是數據庫 — 我們的 AI 主動篩選客源、建議跟進、優化您的工作流程。',
    'platform.why.3.title': '代理整合',
    'platform.why.3.desc': '與我們的營銷代理服務無縫連接，打造全方位增長引擎。',
    'platform.cta.title': '準備好掌控一切？',
    'platform.cta.desc': '開始使用香港地產界最聰明的 CRM 管理您的樓盤和客源。',
    'platform.cta.button': '查看方案',
    'platform.cta.agency': '探索營銷代理',

    // Agency Page
    'agency.badge': '營銷代理',
    'agency.hero.title': '我們為您處理',
    'agency.hero.subtitle': '整個營銷運作',
    'agency.hero.desc': '從 AI 影片製作到精準廣告投放，我們的全方位營銷代理為您處理繁重工作，讓您專注成交。',
    'agency.hero.cta.services': '查看服務及收費',
    'agency.hero.cta.consult': '預約諮詢',
    'agency.services.title': '全方位營銷服務',
    'agency.services.desc': '現代地產代理稱霸市場所需的一切 — 全部為您代勞。',
    'agency.svc.video.title': 'AI 影片製作',
    'agency.svc.video.desc': '我們將您的樓盤照片轉化為電影級影片導覽，配有專業旁白、音樂和動態轉場。48 小時內交付，無需攝影團隊。',
    'agency.svc.ads.title': '精準廣告投放',
    'agency.svc.ads.desc': '我們的演算法分析數千個數據點，找出高意向買家。我們為您投放和優化 Facebook 及 Instagram 廣告，實現最高回報。',
    'agency.svc.content.title': '社交媒體內容',
    'agency.svc.content.desc': '我們為您創作和管理社交媒體內容，包括專業貼文、限時動態和短片，度身訂造配合您的品牌和市場。',
    'agency.svc.drone.title': '航拍影片剪輯',
    'agency.svc.drone.desc': '將您的原始航拍素材交給我們，我們會將其轉化為電影級航拍展示，配以調色、音樂和專業圖形。',
    'agency.svc.staging.title': '虛擬佈置',
    'agency.svc.staging.desc': '數碼化佈置空置房間，幫助買家想像物業的潛力。最具成本效益的方式讓物業感覺像家。',
    'agency.svc.social.title': '社交媒體管理',
    'agency.svc.social.desc': '我們處理您的整個社交媒體策略 — 內容日曆、發佈時間表、社群互動和效能報告。',
    'agency.addons.title': '附加服務',
    'agency.addons.desc': '隨時可購買的一次性服務，助您提升特定樓盤或廣告活動。',
    'agency.addon.videopack.title': '額外影片套裝',
    'agency.addon.videopack.desc': '10 條額外 AI 生成樓盤影片。',
    'agency.addon.imagepack.title': '額外圖片套裝',
    'agency.addon.imagepack.desc': '50 張專業優化樓盤圖片。',
    'agency.addon.voiceover.title': '廣東話配音',
    'agency.addon.voiceover.desc': '為您的影片提供專業廣東話 AI 配音。',
    'agency.addon.staging.title': '虛擬佈置',
    'agency.addon.staging.desc': '為空置物業提供每房間數碼化佈置。',
    'agency.addon.drone.title': '航拍影片剪輯',
    'agency.addon.drone.desc': '專業剪輯您的原始航拍素材。',
    'agency.addon.social.title': '社交媒體套裝',
    'agency.addon.social.desc': '每月社交媒體內容套裝。',
    'agency.addon.portal.title': '品牌專屬網頁',
    'agency.addon.portal.desc': '自訂品牌樓盤網頁設置。',
    'agency.addon.rush.title': '優先處理',
    'agency.addon.rush.desc': '緊急影片項目加急交付。',
    'agency.results.title': '實戰成果',
    'agency.results.desc': '我們的客戶從第一天起就看到可衡量、可驗證的成果。',
    'agency.results.roi': '平均廣告回報率',
    'agency.results.delivery': '影片交付時間',
    'agency.results.cpl': '平均每客源成本',
    'agency.cta.title': '讓我們處理您的營銷',
    'agency.cta.desc': '預約免費諮詢，了解我們的代理如何改變您的業務。',
    'agency.cta.button': '預約諮詢',
    'agency.cta.platform': '探索 CRM 平台',

    // Thank You
    'thankyou.title': '感謝您的查詢！',
    'thankyou.subtitle': '我們已收到您的訊息。',
    'thankyou.desc': '確認郵件已發送至您的信箱。在等待期間，歡迎直接預約 15 分鐘免費諮詢，讓我們更快為您服務。',
    'thankyou.button': '預約諮詢',
    'thankyou.back': '返回首頁',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
